<a href="https://colab.research.google.com/github/juggernautjha/stamatics-ml/blob/main/Assignment_1_Rahul_Jha.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [21]:
array_ones = np.ones(4, dtype = np.int64)
array_ones

array([1, 1, 1, 1])

Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [22]:
mat = np.matrix([[1,2],[3,4]])
mat

matrix([[1, 2],
        [3, 4]])

Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [23]:
dist = np.linspace(3.,10.,50,True)
dist

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [24]:
#trial
x = np.array([[1,2,3], [4,5,6]])
y_1 = np.array([x[0][i] for i in range(3)])
y_2 = np.array([x[1][i] for i in range(3)])
j = np.concatenate((y_1, y_2))

In [25]:
j = np.concatenate((x[0], x[1]))

Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [26]:
y_1 = x[:5]
y_2 = x[5:7]
y_3 = x[7:]


 Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [27]:
x = np.matrix([[1,2], [3,4]])
trace = np.trace(x)
trace
inv = np.linalg.inv(x)
inv
np.matmul(x,inv) #just to check

matrix([[1.0000000e+00, 0.0000000e+00],
        [8.8817842e-16, 1.0000000e+00]])

Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [28]:
x = np.array([[1,4],[3,1]])
y = np.sort(x, axis = 0)
y

array([[1, 1],
       [3, 4]])

Q8 Get the indices that would sort x(as above) along the second axis.


In [29]:
z = np.argsort(x)
z

array([[0, 1],
       [1, 0]])

Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [30]:
arr = np.random.randint(0,10,(2,5))
arr
print(arr)
max = arr.max()
min = arr.min()
print("Max : {0}\nMin : {1}".format(max, min))
index_max = np.where(arr == max)
index_min = np.where(arr == min)
print("\nList of second-indices of max element",index_max[1]) #picks the second element, which is a list of all the y-coordinates so to say
#Now I'll try listing all the co-ordinates. Its gonna be graphic
max_coordinates = zip(index_max[0], index_max[1])
print("Co-ordinate(s) of max-element")
for i in max_coordinates:
  print("({0}, {1})".format(i[0], i[1]))
print("\nList of second-indices of the min element", index_min[1]) #ditto
print("Co-ordinate(s) of min-element")
min_coordinates = zip(index_min[0], index_min[1])
for i in min_coordinates:
  print("({0}, {1})".format(i[0], i[1]))

[[7 9 2 2 9]
 [2 1 8 7 3]]
Max : 9
Min : 1

List of second-indices of max element [1 4]
Co-ordinate(s) of max-element
(0, 1)
(0, 4)

List of second-indices of the min element [1]
Co-ordinate(s) of min-element
(1, 1)


Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [31]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Drop rows that contain a missing value. 

In [32]:
#trial
x = np.array([[1,np.nan, 4], [5,6,7], [9,7,np.nan], [4,5,6]])
np.isnan(x)
y = x[~np.isnan(x).any(axis=1)]
y

array([[5., 6., 7.],
       [4., 5., 6.]])

In [33]:
iris_2d_nomiss = iris_2d[~np.isnan(iris_2d).any(axis=1)]
iris_2d_nomiss

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

Find the correlation between first two columns.

In [34]:
c_1 = iris_2d[:,0]
#print(c_1) #first column
c_2 = iris_2d[:,1]
#print(c_2) #second column
co_rr = np.correlate(c_1, c_2)[0]
co_rr

2670.98

Find the mean,median and standard deviation of column 3.

In [35]:
c_3 = iris_2d[:,2]
mean = np.mean(c_3)
median = np.median(c_3)
stddev = np.std(c_3)
print("Mean: {0}\nMedian: {1}\nStandard Dev: {2}".format(mean, median, stddev))

###Trial
c_3 = iris_2d_nomiss[:,2]
mean = np.mean(c_3)
median = np.median(c_3)
stddev = np.std(c_3)
print("Mean: {0}\nMedian: {1}\nStandard Dev: {2}".format(mean, median, stddev))
###So apparently numoy disregards empty entries while calculating stats

Mean: 3.758666666666666
Median: 4.35
Standard Dev: 1.7585291834055212
Mean: 3.758666666666666
Median: 4.35
Standard Dev: 1.7585291834055212


Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [36]:
pet_len = iris_2d[:,2]
sep_len = iris_2d[:,0]
x = pet_len*sep_len*pet_len*np.pi
x = np.array([[i] for i in x])
new_arr = np.append(iris_2d, x, axis = 1)
new_arr

array([[5.10000000e+00, 3.50000000e+00, 1.40000000e+00, 2.00000000e-01,
        3.14033602e+01],
       [4.90000000e+00, 3.00000000e+00, 1.40000000e+00, 2.00000000e-01,
        3.01718558e+01],
       [4.70000000e+00, 3.20000000e+00, 1.30000000e+00, 2.00000000e-01,
        2.49536704e+01],
       [4.60000000e+00, 3.10000000e+00, 1.50000000e+00, 2.00000000e-01,
        3.25154840e+01],
       [5.00000000e+00, 3.60000000e+00, 1.40000000e+00, 2.00000000e-01,
        3.07876080e+01],
       [5.40000000e+00, 3.90000000e+00, 1.70000000e+00, 4.00000000e-01,
        4.90276950e+01],
       [4.60000000e+00, 3.40000000e+00, 1.40000000e+00, 3.00000000e-01,
        2.83245994e+01],
       [5.00000000e+00, 3.40000000e+00, 1.50000000e+00, 2.00000000e-01,
        3.53429174e+01],
       [4.40000000e+00, 2.90000000e+00, 1.40000000e+00, 2.00000000e-01,
        2.70930950e+01],
       [4.90000000e+00, 3.10000000e+00, 1.50000000e+00, 1.00000000e-01,
        3.46360590e+01],
       [5.40000000e+00, 3.7000

Run the following loaad command and solve the following questions

In [37]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Find the count of unique species.

In [38]:
values, unique = np.unique(iris[:, 4], return_counts=True)
for i in zip(values, unique):
  print("Species: {0} -> Count : {1}".format(str(i[0], 'utf-8'), i[1]))

Species: Iris-setosa -> Count : 50
Species: Iris-versicolor -> Count : 50
Species: Iris-virginica -> Count : 50


Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
Less than 3 –> ‘small’
3-5 –> ‘medium’
‘>=5 –> ‘large’

In [39]:
c_3 = iris_2d[:,2] #third column
y = []
for i in c_3:
  if (i < 3):
    y.append('small')
  elif(i < 5):
    y.append('medium')
  else:
    y.append('large')
  
y

['small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'mediu

Find the most frequent value of petal length (3rd column) in iris dataset

In [40]:
# c_3 = iris[:,2] #couldn't find the mode function in pure numpy, so here goes nothing
# c_3 = [eval(i) for i in c_3]
# c_3.sort()
# c_3
c_3 = [2,4,5,5,5,6,6,7,6,7]
c_3.sort()
max = 0
curr_mode = c_3[0]
curr_max = 0
for i in range(len(c_3)):
  if i == 0:
    curr_max = 1
  elif c_3[i] == c_3[i-1]:
    print(c_3[i], c_3[i-1])
    curr_max += 1
    curr_mode = c_3[i]
  else:
    print(c_3[i], c_3[i-1])
    if curr_max > max:
      max = curr_max

      #curr_mode = c_3[i-1]
    curr_max = 0
print(curr_mode)



4 2
5 4
5 5
5 5
6 5
6 6
6 6
7 6
7 7
7
